# Generated by Django 5.1.5 on 2025-04-21 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='No phone', max_length=255)),
                ('city', models.CharField(default='No phone', max_length=100)),
                ('state', models.CharField(default='No phone', max_length=100)),
                ('zip_code', models.CharField(default='No phone', max_length=20)),
                ('phone', models.CharField(default='No phone', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default='N', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
