# Generated by Django 5.1.5 on 2025-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.TextField(default='a'),
        ),
    ]
